version: '3'

services:
  gsession:
    image: localhost/gsession:latest
    container_name: gsession

    environment:
      - TZ=Asia/Tokyo

    volumes:
      - gsession-data:/opt/data

    networks:
      - containya-network

#    ports:
#      - 8081:8080

volumes:
  gsession-data:
    external: true

networks:
  containya-network:
    external: true
