version: '3'

services:
  gsession:
    image: localhost/gsession
    container_name: 'gsession'

    environment:
      - TZ=Asia/Tokyo

    volumes:
      - gsession-dat:/opt/data

    networks:
      - containya-network

#    ports:
#      - 8081:8080

volumes:
  gsession-dat:
    external: true

networks:
  containya-network:
    external: true
